# 2 "data/maps/Ocean_1/scripts.pory"

# 3 "data/maps/Ocean_1/scripts.pory"
   Ocean_1_MapScripts::
# 4 "data/maps/Ocean_1/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, randomspawnoverworldobject
# 5 "data/maps/Ocean_1/scripts.pory"
	.byte 0

randomspawnoverworldobject::
# 9 "data/maps/Ocean_1/scripts.pory"
	random 500
# 11 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 1
	goto_if_eq randomspawnoverworldobject_2
randomspawnoverworldobject_1:
# 14 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 2
	goto_if_eq randomspawnoverworldobject_5
randomspawnoverworldobject_4:
# 17 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 3
	goto_if_eq randomspawnoverworldobject_8
randomspawnoverworldobject_7:
# 20 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 4
	goto_if_eq randomspawnoverworldobject_11
randomspawnoverworldobject_10:
# 23 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 5
	goto_if_eq randomspawnoverworldobject_14
randomspawnoverworldobject_13:
# 26 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 6
	goto_if_eq randomspawnoverworldobject_17
randomspawnoverworldobject_16:
# 29 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 7
	goto_if_eq randomspawnoverworldobject_20
randomspawnoverworldobject_19:
# 32 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 8
	goto_if_eq randomspawnoverworldobject_23
randomspawnoverworldobject_22:
# 35 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 9
	goto_if_eq randomspawnoverworldobject_26
randomspawnoverworldobject_25:
# 38 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 10
	goto_if_eq randomspawnoverworldobject_29
randomspawnoverworldobject_28:
# 41 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 11
	goto_if_eq randomspawnoverworldobject_32
randomspawnoverworldobject_31:
# 45 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 12
	goto_if_eq randomspawnoverworldobject_35
randomspawnoverworldobject_34:
# 49 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 13
	goto_if_eq randomspawnoverworldobject_38
randomspawnoverworldobject_37:
# 53 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 14
	goto_if_eq randomspawnoverworldobject_41
randomspawnoverworldobject_40:
# 57 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 15
	goto_if_eq randomspawnoverworldobject_44
randomspawnoverworldobject_43:
# 61 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 16
	goto_if_eq randomspawnoverworldobject_47
randomspawnoverworldobject_46:
# 65 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 17
	goto_if_eq randomspawnoverworldobject_50
randomspawnoverworldobject_49:
# 69 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 18
	goto_if_eq randomspawnoverworldobject_53
randomspawnoverworldobject_52:
# 73 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 19
	goto_if_eq randomspawnoverworldobject_56
randomspawnoverworldobject_55:
# 77 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 20
	goto_if_eq randomspawnoverworldobject_59
randomspawnoverworldobject_58:
# 81 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 21
	goto_if_eq randomspawnoverworldobject_62
randomspawnoverworldobject_61:
# 85 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 22
	goto_if_eq randomspawnoverworldobject_65
randomspawnoverworldobject_64:
# 89 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 23
	goto_if_eq randomspawnoverworldobject_68
randomspawnoverworldobject_67:
# 93 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 24
	goto_if_eq randomspawnoverworldobject_71
randomspawnoverworldobject_70:
# 97 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 25
	goto_if_eq randomspawnoverworldobject_74
randomspawnoverworldobject_73:
# 101 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 26
	goto_if_eq randomspawnoverworldobject_77
randomspawnoverworldobject_76:
# 105 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 27
	goto_if_eq randomspawnoverworldobject_80
randomspawnoverworldobject_79:
# 109 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 28
	goto_if_eq randomspawnoverworldobject_83
randomspawnoverworldobject_82:
# 113 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 29
	goto_if_eq randomspawnoverworldobject_86
randomspawnoverworldobject_85:
# 117 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 30
	goto_if_eq randomspawnoverworldobject_89
randomspawnoverworldobject_88:
# 121 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 31
	goto_if_eq randomspawnoverworldobject_92
randomspawnoverworldobject_91:
# 125 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 32
	goto_if_eq randomspawnoverworldobject_95
randomspawnoverworldobject_94:
# 129 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 33
	goto_if_eq randomspawnoverworldobject_98
randomspawnoverworldobject_97:
# 133 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 34
	goto_if_eq randomspawnoverworldobject_101
randomspawnoverworldobject_100:
# 137 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 35
	goto_if_eq randomspawnoverworldobject_104
randomspawnoverworldobject_103:
# 141 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 36
	goto_if_eq randomspawnoverworldobject_107
randomspawnoverworldobject_106:
# 145 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 37
	goto_if_eq randomspawnoverworldobject_110
randomspawnoverworldobject_109:
# 149 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 38
	goto_if_eq randomspawnoverworldobject_113
randomspawnoverworldobject_112:
# 153 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 39
	goto_if_eq randomspawnoverworldobject_116
randomspawnoverworldobject_115:
# 157 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 40
	goto_if_eq randomspawnoverworldobject_119
randomspawnoverworldobject_118:
# 161 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 41
	goto_if_eq randomspawnoverworldobject_122
randomspawnoverworldobject_121:
# 165 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 42
	goto_if_eq randomspawnoverworldobject_125
randomspawnoverworldobject_124:
# 169 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 43
	goto_if_eq randomspawnoverworldobject_128
randomspawnoverworldobject_127:
# 173 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 44
	goto_if_eq randomspawnoverworldobject_131
randomspawnoverworldobject_130:
# 177 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 45
	goto_if_eq randomspawnoverworldobject_134
randomspawnoverworldobject_133:
# 181 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 46
	goto_if_eq randomspawnoverworldobject_137
randomspawnoverworldobject_136:
# 185 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 47
	goto_if_eq randomspawnoverworldobject_140
randomspawnoverworldobject_139:
# 189 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 48
	goto_if_eq randomspawnoverworldobject_143
randomspawnoverworldobject_142:
# 193 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 49
	goto_if_eq randomspawnoverworldobject_146
randomspawnoverworldobject_145:
# 197 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 50
	goto_if_eq randomspawnoverworldobject_149
randomspawnoverworldobject_148:
# 201 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 51
	goto_if_eq randomspawnoverworldobject_152
randomspawnoverworldobject_151:
# 205 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 52
	goto_if_eq randomspawnoverworldobject_155
randomspawnoverworldobject_154:
# 209 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 53
	goto_if_eq randomspawnoverworldobject_158
randomspawnoverworldobject_157:
# 213 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 54
	goto_if_eq randomspawnoverworldobject_161
randomspawnoverworldobject_160:
# 217 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 55
	goto_if_eq randomspawnoverworldobject_164
randomspawnoverworldobject_163:
# 221 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 56
	goto_if_eq randomspawnoverworldobject_167
randomspawnoverworldobject_166:
# 226 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 57
	goto_if_eq randomspawnoverworldobject_170
randomspawnoverworldobject_169:
# 231 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 58
	goto_if_eq randomspawnoverworldobject_173
randomspawnoverworldobject_172:
# 236 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 59
	goto_if_eq randomspawnoverworldobject_176
randomspawnoverworldobject_175:
# 241 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 60
	goto_if_eq randomspawnoverworldobject_179
randomspawnoverworldobject_178:
# 246 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 61
	goto_if_eq randomspawnoverworldobject_182
randomspawnoverworldobject_181:
# 251 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 62
	goto_if_eq randomspawnoverworldobject_185
randomspawnoverworldobject_184:
# 256 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 63
	goto_if_eq randomspawnoverworldobject_188
randomspawnoverworldobject_187:
# 261 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 64
	goto_if_eq randomspawnoverworldobject_191
randomspawnoverworldobject_190:
# 266 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 65
	goto_if_eq randomspawnoverworldobject_194
randomspawnoverworldobject_193:
# 271 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 66
	goto_if_eq randomspawnoverworldobject_197
randomspawnoverworldobject_196:
# 276 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 67
	goto_if_eq randomspawnoverworldobject_200
randomspawnoverworldobject_199:
# 281 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 68
	goto_if_eq randomspawnoverworldobject_203
randomspawnoverworldobject_202:
# 286 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 69
	goto_if_eq randomspawnoverworldobject_206
randomspawnoverworldobject_205:
# 291 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 70
	goto_if_eq randomspawnoverworldobject_209
randomspawnoverworldobject_208:
# 296 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 71
	goto_if_eq randomspawnoverworldobject_212
randomspawnoverworldobject_211:
# 301 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 72
	goto_if_eq randomspawnoverworldobject_215
randomspawnoverworldobject_214:
# 306 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 73
	goto_if_eq randomspawnoverworldobject_218
randomspawnoverworldobject_217:
# 311 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 74
	goto_if_eq randomspawnoverworldobject_221
randomspawnoverworldobject_220:
# 316 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 75
	goto_if_eq randomspawnoverworldobject_224
randomspawnoverworldobject_223:
# 321 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 76
	goto_if_eq randomspawnoverworldobject_227
randomspawnoverworldobject_226:
# 326 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 77
	goto_if_eq randomspawnoverworldobject_230
randomspawnoverworldobject_229:
# 331 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 78
	goto_if_eq randomspawnoverworldobject_233
randomspawnoverworldobject_232:
# 336 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 79
	goto_if_eq randomspawnoverworldobject_236
randomspawnoverworldobject_235:
# 341 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 80
	goto_if_eq randomspawnoverworldobject_239
randomspawnoverworldobject_238:
# 346 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 81
	goto_if_eq randomspawnoverworldobject_242
randomspawnoverworldobject_241:
# 351 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 82
	goto_if_eq randomspawnoverworldobject_245
randomspawnoverworldobject_244:
# 356 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 83
	goto_if_eq randomspawnoverworldobject_248
randomspawnoverworldobject_247:
# 361 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 84
	goto_if_eq randomspawnoverworldobject_251
randomspawnoverworldobject_250:
# 366 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 85
	goto_if_eq randomspawnoverworldobject_254
randomspawnoverworldobject_253:
# 371 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 86
	goto_if_eq randomspawnoverworldobject_257
randomspawnoverworldobject_256:
# 376 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 87
	goto_if_eq randomspawnoverworldobject_260
randomspawnoverworldobject_259:
# 381 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 88
	goto_if_eq randomspawnoverworldobject_263
randomspawnoverworldobject_262:
# 386 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 89
	goto_if_eq randomspawnoverworldobject_266
randomspawnoverworldobject_265:
# 391 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 90
	goto_if_eq randomspawnoverworldobject_269
randomspawnoverworldobject_268:
# 396 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 91
	goto_if_eq randomspawnoverworldobject_272
randomspawnoverworldobject_271:
# 401 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 92
	goto_if_eq randomspawnoverworldobject_275
randomspawnoverworldobject_274:
# 406 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 93
	goto_if_eq randomspawnoverworldobject_278
randomspawnoverworldobject_277:
# 411 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 94
	goto_if_eq randomspawnoverworldobject_281
randomspawnoverworldobject_280:
# 416 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 95
	goto_if_eq randomspawnoverworldobject_284
randomspawnoverworldobject_283:
# 421 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 96
	goto_if_eq randomspawnoverworldobject_287
randomspawnoverworldobject_286:
# 426 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 97
	goto_if_eq randomspawnoverworldobject_290
randomspawnoverworldobject_289:
# 431 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 98
	goto_if_eq randomspawnoverworldobject_293
randomspawnoverworldobject_292:
# 436 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 99
	goto_if_eq randomspawnoverworldobject_296
randomspawnoverworldobject_295:
# 441 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 100
	goto_if_eq randomspawnoverworldobject_299
randomspawnoverworldobject_298:
# 446 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 101
	goto_if_eq randomspawnoverworldobject_302
randomspawnoverworldobject_301:
# 451 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 102
	goto_if_eq randomspawnoverworldobject_305
randomspawnoverworldobject_304:
# 456 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 103
	goto_if_eq randomspawnoverworldobject_308
randomspawnoverworldobject_307:
# 461 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 104
	goto_if_eq randomspawnoverworldobject_311
randomspawnoverworldobject_310:
# 466 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 105
	goto_if_eq randomspawnoverworldobject_314
randomspawnoverworldobject_313:
# 471 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 106
	goto_if_eq randomspawnoverworldobject_317
randomspawnoverworldobject_316:
# 476 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 107
	goto_if_eq randomspawnoverworldobject_320
randomspawnoverworldobject_319:
# 481 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 108
	goto_if_eq randomspawnoverworldobject_323
randomspawnoverworldobject_322:
# 486 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 109
	goto_if_eq randomspawnoverworldobject_326
randomspawnoverworldobject_325:
# 491 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 110
	goto_if_eq randomspawnoverworldobject_329
randomspawnoverworldobject_328:
# 496 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 111
	goto_if_eq randomspawnoverworldobject_332
randomspawnoverworldobject_331:
# 501 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 112
	goto_if_eq randomspawnoverworldobject_335
randomspawnoverworldobject_334:
# 506 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 113
	goto_if_eq randomspawnoverworldobject_338
randomspawnoverworldobject_337:
# 511 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 114
	goto_if_eq randomspawnoverworldobject_341
randomspawnoverworldobject_340:
# 516 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 115
	goto_if_eq randomspawnoverworldobject_344
randomspawnoverworldobject_343:
# 521 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 116
	goto_if_eq randomspawnoverworldobject_347
randomspawnoverworldobject_346:
# 526 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 117
	goto_if_eq randomspawnoverworldobject_350
randomspawnoverworldobject_349:
# 531 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 118
	goto_if_eq randomspawnoverworldobject_353
randomspawnoverworldobject_352:
# 536 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 119
	goto_if_eq randomspawnoverworldobject_356
randomspawnoverworldobject_355:
# 541 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 120
	goto_if_eq randomspawnoverworldobject_359
randomspawnoverworldobject_358:
# 546 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 121
	goto_if_eq randomspawnoverworldobject_362
randomspawnoverworldobject_361:
# 551 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 122
	goto_if_eq randomspawnoverworldobject_365
randomspawnoverworldobject_364:
# 556 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 123
	goto_if_eq randomspawnoverworldobject_368
randomspawnoverworldobject_367:
# 561 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 124
	goto_if_eq randomspawnoverworldobject_371
randomspawnoverworldobject_370:
# 566 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 125
	goto_if_eq randomspawnoverworldobject_374
randomspawnoverworldobject_373:
# 571 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 126
	goto_if_eq randomspawnoverworldobject_377
randomspawnoverworldobject_376:
# 576 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 127
	goto_if_eq randomspawnoverworldobject_380
randomspawnoverworldobject_379:
# 581 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 128
	goto_if_eq randomspawnoverworldobject_383
randomspawnoverworldobject_382:
# 586 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 129
	goto_if_eq randomspawnoverworldobject_386
randomspawnoverworldobject_385:
# 591 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 130
	goto_if_eq randomspawnoverworldobject_389
randomspawnoverworldobject_388:
# 596 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 131
	goto_if_eq randomspawnoverworldobject_392
randomspawnoverworldobject_391:
# 601 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 132
	goto_if_eq randomspawnoverworldobject_395
randomspawnoverworldobject_394:
# 606 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 133
	goto_if_eq randomspawnoverworldobject_398
randomspawnoverworldobject_397:
# 611 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 134
	goto_if_eq randomspawnoverworldobject_401
randomspawnoverworldobject_400:
# 617 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 135
	goto_if_eq randomspawnoverworldobject_404
randomspawnoverworldobject_403:
# 623 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 136
	goto_if_eq randomspawnoverworldobject_407
randomspawnoverworldobject_406:
# 629 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 137
	goto_if_eq randomspawnoverworldobject_410
randomspawnoverworldobject_409:
# 635 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 138
	goto_if_eq randomspawnoverworldobject_413
randomspawnoverworldobject_412:
# 641 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 139
	goto_if_eq randomspawnoverworldobject_416
randomspawnoverworldobject_415:
# 647 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 140
	goto_if_eq randomspawnoverworldobject_419
randomspawnoverworldobject_418:
# 653 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 141
	goto_if_eq randomspawnoverworldobject_422
randomspawnoverworldobject_421:
# 659 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 142
	goto_if_eq randomspawnoverworldobject_425
randomspawnoverworldobject_424:
# 665 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 143
	goto_if_eq randomspawnoverworldobject_428
randomspawnoverworldobject_427:
# 671 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 144
	goto_if_eq randomspawnoverworldobject_431
randomspawnoverworldobject_430:
# 677 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 145
	goto_if_eq randomspawnoverworldobject_434
randomspawnoverworldobject_433:
# 683 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 146
	goto_if_eq randomspawnoverworldobject_437
randomspawnoverworldobject_436:
# 689 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 147
	goto_if_eq randomspawnoverworldobject_440
randomspawnoverworldobject_439:
# 695 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 148
	goto_if_eq randomspawnoverworldobject_443
randomspawnoverworldobject_442:
# 701 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 149
	goto_if_eq randomspawnoverworldobject_446
randomspawnoverworldobject_445:
# 707 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 150
	goto_if_eq randomspawnoverworldobject_449
randomspawnoverworldobject_448:
# 713 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 151
	goto_if_eq randomspawnoverworldobject_452
randomspawnoverworldobject_451:
# 719 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 152
	goto_if_eq randomspawnoverworldobject_455
randomspawnoverworldobject_454:
# 725 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 153
	goto_if_eq randomspawnoverworldobject_458
randomspawnoverworldobject_457:
# 731 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 154
	goto_if_eq randomspawnoverworldobject_461
randomspawnoverworldobject_460:
# 737 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 155
	goto_if_eq randomspawnoverworldobject_464
randomspawnoverworldobject_463:
# 743 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 156
	goto_if_eq randomspawnoverworldobject_467
randomspawnoverworldobject_466:
# 749 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 157
	goto_if_eq randomspawnoverworldobject_470
randomspawnoverworldobject_469:
# 755 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 158
	goto_if_eq randomspawnoverworldobject_473
randomspawnoverworldobject_472:
# 761 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 159
	goto_if_eq randomspawnoverworldobject_476
randomspawnoverworldobject_475:
# 767 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 160
	goto_if_eq randomspawnoverworldobject_479
randomspawnoverworldobject_478:
# 773 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 161
	goto_if_eq randomspawnoverworldobject_482
randomspawnoverworldobject_481:
# 779 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 162
	goto_if_eq randomspawnoverworldobject_485
randomspawnoverworldobject_484:
# 785 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 163
	goto_if_eq randomspawnoverworldobject_488
randomspawnoverworldobject_487:
# 791 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 164
	goto_if_eq randomspawnoverworldobject_491
randomspawnoverworldobject_490:
# 797 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 165
	goto_if_eq randomspawnoverworldobject_494
randomspawnoverworldobject_493:
# 803 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 166
	goto_if_eq randomspawnoverworldobject_497
randomspawnoverworldobject_496:
# 809 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 167
	goto_if_eq randomspawnoverworldobject_500
randomspawnoverworldobject_499:
# 815 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 168
	goto_if_eq randomspawnoverworldobject_503
randomspawnoverworldobject_502:
# 821 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 169
	goto_if_eq randomspawnoverworldobject_506
randomspawnoverworldobject_505:
# 827 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 170
	goto_if_eq randomspawnoverworldobject_509
randomspawnoverworldobject_508:
# 833 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 171
	goto_if_eq randomspawnoverworldobject_512
randomspawnoverworldobject_511:
# 839 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 172
	goto_if_eq randomspawnoverworldobject_515
randomspawnoverworldobject_514:
# 845 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 173
	goto_if_eq randomspawnoverworldobject_518
randomspawnoverworldobject_517:
# 851 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 174
	goto_if_eq randomspawnoverworldobject_521
randomspawnoverworldobject_520:
# 857 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 175
	goto_if_eq randomspawnoverworldobject_524
randomspawnoverworldobject_523:
# 863 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 176
	goto_if_eq randomspawnoverworldobject_527
randomspawnoverworldobject_526:
# 869 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 177
	goto_if_eq randomspawnoverworldobject_530
randomspawnoverworldobject_529:
# 875 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 178
	goto_if_eq randomspawnoverworldobject_533
randomspawnoverworldobject_532:
# 881 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 179
	goto_if_eq randomspawnoverworldobject_536
randomspawnoverworldobject_535:
# 887 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 180
	goto_if_eq randomspawnoverworldobject_539
randomspawnoverworldobject_538:
# 893 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 181
	goto_if_eq randomspawnoverworldobject_542
randomspawnoverworldobject_541:
# 899 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 182
	goto_if_eq randomspawnoverworldobject_545
randomspawnoverworldobject_544:
# 905 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 183
	goto_if_eq randomspawnoverworldobject_548
randomspawnoverworldobject_547:
# 911 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 184
	goto_if_eq randomspawnoverworldobject_551
randomspawnoverworldobject_550:
# 917 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 185
	goto_if_eq randomspawnoverworldobject_554
randomspawnoverworldobject_553:
# 923 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 186
	goto_if_eq randomspawnoverworldobject_557
randomspawnoverworldobject_556:
# 929 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 187
	goto_if_eq randomspawnoverworldobject_560
randomspawnoverworldobject_559:
# 935 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 188
	goto_if_eq randomspawnoverworldobject_563
randomspawnoverworldobject_562:
# 941 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 189
	goto_if_eq randomspawnoverworldobject_566
randomspawnoverworldobject_565:
# 947 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 190
	goto_if_eq randomspawnoverworldobject_569
randomspawnoverworldobject_568:
# 953 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 191
	goto_if_eq randomspawnoverworldobject_572
randomspawnoverworldobject_571:
# 959 "data/maps/Ocean_1/scripts.pory"
	compare VAR_RESULT, 192
	goto_if_eq randomspawnoverworldobject_574
	return

randomspawnoverworldobject_2:
# 12 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
	goto randomspawnoverworldobject_1

randomspawnoverworldobject_5:
# 15 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
	goto randomspawnoverworldobject_4

randomspawnoverworldobject_8:
# 18 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
	goto randomspawnoverworldobject_7

randomspawnoverworldobject_11:
# 21 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_10

randomspawnoverworldobject_14:
# 24 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_13

randomspawnoverworldobject_17:
# 27 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_16

randomspawnoverworldobject_20:
# 30 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_19

randomspawnoverworldobject_23:
# 33 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_22

randomspawnoverworldobject_26:
# 36 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_25

randomspawnoverworldobject_29:
# 39 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_28

randomspawnoverworldobject_32:
# 42 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 43 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
	goto randomspawnoverworldobject_31

randomspawnoverworldobject_35:
# 46 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 47 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
	goto randomspawnoverworldobject_34

randomspawnoverworldobject_38:
# 50 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 51 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_37

randomspawnoverworldobject_41:
# 54 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 55 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_40

randomspawnoverworldobject_44:
# 58 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 59 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_43

randomspawnoverworldobject_47:
# 62 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 63 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_46

randomspawnoverworldobject_50:
# 66 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 67 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_49

randomspawnoverworldobject_53:
# 70 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 71 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_52

randomspawnoverworldobject_56:
# 74 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 75 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_55

randomspawnoverworldobject_59:
# 78 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 79 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
	goto randomspawnoverworldobject_58

randomspawnoverworldobject_62:
# 82 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 83 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_61

randomspawnoverworldobject_65:
# 86 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 87 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_64

randomspawnoverworldobject_68:
# 90 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 91 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_67

randomspawnoverworldobject_71:
# 94 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 95 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_70

randomspawnoverworldobject_74:
# 98 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 99 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_73

randomspawnoverworldobject_77:
# 102 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 103 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_76

randomspawnoverworldobject_80:
# 106 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 107 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_79

randomspawnoverworldobject_83:
# 110 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 111 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_82

randomspawnoverworldobject_86:
# 114 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 115 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_85

randomspawnoverworldobject_89:
# 118 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 119 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_88

randomspawnoverworldobject_92:
# 122 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 123 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_91

randomspawnoverworldobject_95:
# 126 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 127 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_94

randomspawnoverworldobject_98:
# 130 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 131 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_97

randomspawnoverworldobject_101:
# 134 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 135 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_100

randomspawnoverworldobject_104:
# 138 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 139 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_103

randomspawnoverworldobject_107:
# 142 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 143 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_106

randomspawnoverworldobject_110:
# 146 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 147 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_109

randomspawnoverworldobject_113:
# 150 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 151 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_112

randomspawnoverworldobject_116:
# 154 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 155 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_115

randomspawnoverworldobject_119:
# 158 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 159 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_118

randomspawnoverworldobject_122:
# 162 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 163 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_121

randomspawnoverworldobject_125:
# 166 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 167 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_124

randomspawnoverworldobject_128:
# 170 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 171 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_127

randomspawnoverworldobject_131:
# 174 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 175 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_130

randomspawnoverworldobject_134:
# 178 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 179 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_133

randomspawnoverworldobject_137:
# 182 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 183 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_136

randomspawnoverworldobject_140:
# 186 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 187 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_139

randomspawnoverworldobject_143:
# 190 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 191 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_142

randomspawnoverworldobject_146:
# 194 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 195 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_145

randomspawnoverworldobject_149:
# 198 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 199 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_148

randomspawnoverworldobject_152:
# 202 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 203 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_151

randomspawnoverworldobject_155:
# 206 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 207 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_154

randomspawnoverworldobject_158:
# 210 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 211 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_157

randomspawnoverworldobject_161:
# 214 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 215 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_160

randomspawnoverworldobject_164:
# 218 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 219 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_163

randomspawnoverworldobject_167:
# 222 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 223 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 224 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
	goto randomspawnoverworldobject_166

randomspawnoverworldobject_170:
# 227 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 228 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 229 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_169

randomspawnoverworldobject_173:
# 232 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 233 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 234 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_172

randomspawnoverworldobject_176:
# 237 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 238 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 239 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_175

randomspawnoverworldobject_179:
# 242 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 243 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 244 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_178

randomspawnoverworldobject_182:
# 247 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 248 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 249 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_181

randomspawnoverworldobject_185:
# 252 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 253 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 254 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_184

randomspawnoverworldobject_188:
# 257 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 258 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 259 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_187

randomspawnoverworldobject_191:
# 262 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 263 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 264 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_190

randomspawnoverworldobject_194:
# 267 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 268 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 269 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_193

randomspawnoverworldobject_197:
# 272 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 273 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 274 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_196

randomspawnoverworldobject_200:
# 277 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 278 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 279 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_199

randomspawnoverworldobject_203:
# 282 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 283 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 284 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_202

randomspawnoverworldobject_206:
# 287 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 288 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 289 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_205

randomspawnoverworldobject_209:
# 292 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 293 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 294 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_208

randomspawnoverworldobject_212:
# 297 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 298 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 299 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_211

randomspawnoverworldobject_215:
# 302 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 303 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 304 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_214

randomspawnoverworldobject_218:
# 307 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 308 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 309 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_217

randomspawnoverworldobject_221:
# 312 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 313 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 314 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_220

randomspawnoverworldobject_224:
# 317 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 318 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 319 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_223

randomspawnoverworldobject_227:
# 322 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 323 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 324 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_226

randomspawnoverworldobject_230:
# 327 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 328 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 329 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_229

randomspawnoverworldobject_233:
# 332 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 333 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 334 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_232

randomspawnoverworldobject_236:
# 337 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 338 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 339 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_235

randomspawnoverworldobject_239:
# 342 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 343 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 344 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_238

randomspawnoverworldobject_242:
# 347 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 348 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 349 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_241

randomspawnoverworldobject_245:
# 352 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 353 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 354 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_244

randomspawnoverworldobject_248:
# 357 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 358 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 359 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_247

randomspawnoverworldobject_251:
# 362 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 363 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 364 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_250

randomspawnoverworldobject_254:
# 367 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 368 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 369 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_253

randomspawnoverworldobject_257:
# 372 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 373 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 374 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_256

randomspawnoverworldobject_260:
# 377 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 378 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 379 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_259

randomspawnoverworldobject_263:
# 382 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 383 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 384 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_262

randomspawnoverworldobject_266:
# 387 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 388 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 389 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_265

randomspawnoverworldobject_269:
# 392 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 393 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 394 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_268

randomspawnoverworldobject_272:
# 397 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 398 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 399 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_271

randomspawnoverworldobject_275:
# 402 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 403 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 404 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_274

randomspawnoverworldobject_278:
# 407 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 408 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 409 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_277

randomspawnoverworldobject_281:
# 412 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 413 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 414 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_280

randomspawnoverworldobject_284:
# 417 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 418 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 419 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_283

randomspawnoverworldobject_287:
# 422 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 423 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 424 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_286

randomspawnoverworldobject_290:
# 427 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 428 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 429 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_289

randomspawnoverworldobject_293:
# 432 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 433 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 434 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_292

randomspawnoverworldobject_296:
# 437 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 438 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 439 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_295

randomspawnoverworldobject_299:
# 442 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 443 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 444 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_298

randomspawnoverworldobject_302:
# 447 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 448 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 449 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_301

randomspawnoverworldobject_305:
# 452 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 453 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 454 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_304

randomspawnoverworldobject_308:
# 457 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 458 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 459 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_307

randomspawnoverworldobject_311:
# 462 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 463 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 464 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_310

randomspawnoverworldobject_314:
# 467 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 468 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 469 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_313

randomspawnoverworldobject_317:
# 472 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 473 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 474 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_316

randomspawnoverworldobject_320:
# 477 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 478 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 479 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_319

randomspawnoverworldobject_323:
# 482 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 483 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 484 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_322

randomspawnoverworldobject_326:
# 487 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 488 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 489 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_325

randomspawnoverworldobject_329:
# 492 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 493 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 494 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_328

randomspawnoverworldobject_332:
# 497 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 498 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 499 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_331

randomspawnoverworldobject_335:
# 502 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
# 503 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
# 504 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_334

randomspawnoverworldobject_338:
# 507 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 508 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 509 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_337

randomspawnoverworldobject_341:
# 512 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 513 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 514 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_340

randomspawnoverworldobject_344:
# 517 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 518 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 519 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_343

randomspawnoverworldobject_347:
# 522 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 523 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 524 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_346

randomspawnoverworldobject_350:
# 527 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 528 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 529 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_349

randomspawnoverworldobject_353:
# 532 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 533 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 534 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_352

randomspawnoverworldobject_356:
# 537 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 538 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 539 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_355

randomspawnoverworldobject_359:
# 542 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 543 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 544 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_358

randomspawnoverworldobject_362:
# 547 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 548 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 549 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_361

randomspawnoverworldobject_365:
# 552 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 553 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 554 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_364

randomspawnoverworldobject_368:
# 557 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 558 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 559 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_367

randomspawnoverworldobject_371:
# 562 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 563 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 564 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_370

randomspawnoverworldobject_374:
# 567 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 568 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 569 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_373

randomspawnoverworldobject_377:
# 572 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 573 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 574 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_376

randomspawnoverworldobject_380:
# 577 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 578 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 579 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_379

randomspawnoverworldobject_383:
# 582 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 583 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 584 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_382

randomspawnoverworldobject_386:
# 587 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 588 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 589 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_385

randomspawnoverworldobject_389:
# 592 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 593 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 594 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_388

randomspawnoverworldobject_392:
# 597 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 598 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 599 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_391

randomspawnoverworldobject_395:
# 602 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 603 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 604 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_394

randomspawnoverworldobject_398:
# 607 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 608 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 609 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_397

randomspawnoverworldobject_401:
# 612 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 613 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 614 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 615 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
	goto randomspawnoverworldobject_400

randomspawnoverworldobject_404:
# 618 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 619 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 620 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 621 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_403

randomspawnoverworldobject_407:
# 624 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 625 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 626 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 627 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_406

randomspawnoverworldobject_410:
# 630 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 631 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 632 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 633 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_409

randomspawnoverworldobject_413:
# 636 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 637 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 638 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 639 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_412

randomspawnoverworldobject_416:
# 642 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 643 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 644 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 645 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_415

randomspawnoverworldobject_419:
# 648 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 649 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 650 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 651 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_418

randomspawnoverworldobject_422:
# 654 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 655 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 656 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 657 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_421

randomspawnoverworldobject_425:
# 660 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 661 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 662 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 663 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_424

randomspawnoverworldobject_428:
# 666 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 667 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 668 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 669 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_427

randomspawnoverworldobject_431:
# 672 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 673 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 674 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 675 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_430

randomspawnoverworldobject_434:
# 678 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 679 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 680 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 681 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_433

randomspawnoverworldobject_437:
# 684 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 685 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 686 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 687 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_436

randomspawnoverworldobject_440:
# 690 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 691 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 692 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 693 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_439

randomspawnoverworldobject_443:
# 696 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 697 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 698 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 699 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_442

randomspawnoverworldobject_446:
# 702 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 703 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 704 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 705 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_445

randomspawnoverworldobject_449:
# 708 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 709 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 710 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 711 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_448

randomspawnoverworldobject_452:
# 714 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 715 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 716 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 717 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_451

randomspawnoverworldobject_455:
# 720 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 721 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 722 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 723 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_454

randomspawnoverworldobject_458:
# 726 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 727 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 728 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 729 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_457

randomspawnoverworldobject_461:
# 732 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 733 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 734 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 735 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
	goto randomspawnoverworldobject_460

randomspawnoverworldobject_464:
# 738 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 739 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 740 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 741 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_463

randomspawnoverworldobject_467:
# 744 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 745 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 746 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 747 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_466

randomspawnoverworldobject_470:
# 750 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 751 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 752 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 753 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_469

randomspawnoverworldobject_473:
# 756 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 757 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 758 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 759 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_472

randomspawnoverworldobject_476:
# 762 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 763 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 764 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 765 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_475

randomspawnoverworldobject_479:
# 768 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 769 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 770 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 771 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_478

randomspawnoverworldobject_482:
# 774 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 775 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 776 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 777 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_481

randomspawnoverworldobject_485:
# 780 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 781 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 782 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 783 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_484

randomspawnoverworldobject_488:
# 786 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 787 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 788 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 789 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_487

randomspawnoverworldobject_491:
# 792 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 793 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 794 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 795 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
	goto randomspawnoverworldobject_490

randomspawnoverworldobject_494:
# 798 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 799 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 800 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 801 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_493

randomspawnoverworldobject_497:
# 804 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 805 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 806 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 807 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_496

randomspawnoverworldobject_500:
# 810 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 811 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 812 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 813 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_499

randomspawnoverworldobject_503:
# 816 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 817 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 818 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 819 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
	goto randomspawnoverworldobject_502

randomspawnoverworldobject_506:
# 822 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 823 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 824 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 825 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_505

randomspawnoverworldobject_509:
# 828 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 829 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 830 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 831 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_508

randomspawnoverworldobject_512:
# 834 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 835 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 836 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 837 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_511

randomspawnoverworldobject_515:
# 840 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 841 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 842 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 843 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_514

randomspawnoverworldobject_518:
# 846 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 847 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 848 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 849 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_517

randomspawnoverworldobject_521:
# 852 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 853 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 854 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 855 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_520

randomspawnoverworldobject_524:
# 858 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 859 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 860 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 861 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_523

randomspawnoverworldobject_527:
# 864 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 865 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 866 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 867 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_526

randomspawnoverworldobject_530:
# 870 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 871 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 872 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 873 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_529

randomspawnoverworldobject_533:
# 876 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 877 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 878 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 879 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_532

randomspawnoverworldobject_536:
# 882 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 883 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 884 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 885 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_535

randomspawnoverworldobject_539:
# 888 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 889 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 890 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 891 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_538

randomspawnoverworldobject_542:
# 894 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 895 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 896 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 897 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_541

randomspawnoverworldobject_545:
# 900 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 901 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 902 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 903 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_544

randomspawnoverworldobject_548:
# 906 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 907 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_6
# 908 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_1
# 909 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_547

randomspawnoverworldobject_551:
# 912 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 913 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 914 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 915 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_550

randomspawnoverworldobject_554:
# 918 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 919 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 920 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 921 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_553

randomspawnoverworldobject_557:
# 924 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 925 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 926 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_4
# 927 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_556

randomspawnoverworldobject_560:
# 930 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 931 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 932 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 933 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_559

randomspawnoverworldobject_563:
# 936 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 937 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 938 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 939 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_562

randomspawnoverworldobject_566:
# 942 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 943 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 944 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_3
# 945 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	goto randomspawnoverworldobject_565

randomspawnoverworldobject_569:
# 948 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 949 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 950 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 951 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_POKEMON_CENTER_2F_MYSTERY_GIFT_MAN
	goto randomspawnoverworldobject_568

randomspawnoverworldobject_572:
# 954 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 955 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 956 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 957 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_APPRENTICE
	goto randomspawnoverworldobject_571

randomspawnoverworldobject_574:
# 960 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_7
# 961 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_5
# 962 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_UNION_ROOM_PLAYER_2
# 963 "data/maps/Ocean_1/scripts.pory"
	clearflag FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
	return

